service: my-serverless-service

provider:
  environment:
    DYNAMODB_TABLE: Messages
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:UpdateItem'
      Resource: 'arn:aws:dynamodb:eu-north-1:977099030879:table/Messages'
  name: aws
  runtime: nodejs20.x

functions:
  postMessage:
    handler: lambda/postMessage.handler
    events:
      - http:
          path: post-message
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  getMessages:
    handler: lambda/getMessages.handler
    events:
      - http:
          path: get-messages
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
  editMessages:
    handler: lambda/editMessages.handler
    events:
      - http:
          path: edit-message
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
